namespace RiotWebProfiles.Models
{
    public class ChallengesDto
    {
        public int? abilityUses { get; set; }
        public int? acesBefore15Minutes { get; set; }
        public int? alliedJungleMonsterKills { get; set; }
        public int? baronTakedowns { get; set; }
        public double? blastConeOppositeOpponentCount { get; set; }
        public double? bountyGold { get; set; }
        public int? buffsStolen { get; set; }
        public int? controlWardsPlaced { get; set; }
        public int? damagePerMinute { get; set; }
        public int? damageTakenOnTeamPercentage { get; set; }
        public double? dancedWithRiftHerald { get; set; }
        public int? deathsByEnemyChamps { get; set; }
        public int? dodgeSkillShotsSmallWindow { get; set; }
        public int? doubleAces { get; set; }
        public int? dragonTakedowns { get; set; }
        public int? effectiveHealAndShielding { get; set; }
        public int? elderDragonKillsWithOpposingSoul { get; set; }
        public int? elderDragonMultikills { get; set; }
        public int? enemyChampionImmobilizations { get; set; }
        public int? enemyJungleMonsterKills { get; set; }
        public int? epicMonsterKillsNearEnemyJungler { get; set; }
        public int? epicMonsterKillsWithin30SecondsOfSpawn { get; set; }
        public int? epicMonsterSteals { get; set; }
        public int? epicMonsterStolenWithoutSmite { get; set; }
        public int? firstTurretKilled { get; set; }
        public int? flawlessAces { get; set; }
        public int? fullTeamTakedown { get; set; }
        public double? gameLength { get; set; }
        public int? getTakedownsInAllLanesEarlyJungleAsLaner { get; set; }
        public int? goldPerMinute { get; set; }
        public int? hadOpenNexus { get; set; }
        public int? immobilizeAndKillWithAlly { get; set; }
        public int? initialBuffCount { get; set; }
        public int? initialCrabCount { get; set; }
        public int? jungleCsBefore10Minutes { get; set; }
        public int? junglerKillsEarlyJungle { get; set; }
        public int? junglerTakedownsNearDamagedEpicMonster { get; set; }
        public int? kTurretsDestroyedBeforePlatesFall { get; set; }
        public int? kda { get; set; }
        public int? killAfterHiddenWithAlly { get; set; }
        public int? killParticipation { get; set; }
        public int? killedChampTookFullTeamDamageSurvived { get; set; }
        public int? killingSprees { get; set; }
        public int? killsNearEnemyTurret { get; set; }
        public int? killsOnLanersEarlyJungleAsJungler { get; set; }
        public int? killsOnRecentlyHealedByAramPack { get; set; }
        public int? killsUnderOwnTurret { get; set; }
        public int? killsWithHelpFromEpicMonster { get; set; }
        public int? knockEnemyIntoTeamAndKill { get; set; }
        public int? landSkillShotsEarlyGame { get; set; }
        public int? laneMinionsFirst10Minutes { get; set; }
        public int? legendaryCount { get; set; }
        public int? lostAnInhibitor { get; set; }
        public int? maxKillDeficit { get; set; }
        public int? multiKillOneSpell { get; set; }
        public int? multikills { get; set; }
        public int? multikillsAfterAggressiveFlash { get; set; }
        public int? outerTurretExecutesBefore10Minutes { get; set; }
        public int? outnumberedKills { get; set; }
        public int? perfectDragonSoulsTaken { get; set; }
        public int? perfectGame { get; set; }
        public int? pickKillWithAlly { get; set; }
        public int? playedChampSelectPosition { get; set; }
        public int? poroExplosions { get; set; }
        public int? quickCleanse { get; set; }
        public int? quickFirstTurret { get; set; }
        public int? quickSoloKills { get; set; }
        public int? riftHeraldTakedowns { get; set; }
        public int? saveAllyFromDeath { get; set; }
        public int? scuttleCrabKills { get; set; }
        public int? skillshotsDodged { get; set; }
        public int? skillshotsHit { get; set; }
        public int? snowballsHit { get; set; }
        public int? soloBaronKills { get; set; }
        public int? soloKills { get; set; }
        public int? stealthWardsPlaced { get; set; }
        public int? survivedSingleDigitHpCount { get; set; }
        public int? takedownOnFirstTurret { get; set; }
        public int? takedowns { get; set; }
        public int? takedownsAfterGainingLevelAdvantage { get; set; }
        public int? takedownsBeforeJungleMinionSpawn { get; set; }
        public int? takedownsFirstXMinutes { get; set; }
        public int? takedownsInAlcove { get; set; }
        public int? takedownsInEnemyFountain { get; set; }
        public int? teamBaronKills { get; set; }
        public int? teamDamagePercentage { get; set; }
        public int? teamElderDragonKills { get; set; }
        public int? teamRiftHeraldKills { get; set; }
        public int? tookLargeDamageSurvived { get; set; }
        public int? turretPlatesTaken { get; set; }
        public int? turretsTakenWithRiftHerald { get; set; }
        public int? twentyMinionsIn3SecondsCount { get; set; }
        public int? twoWardsOneSweeperCount { get; set; }
        public int? unseenRecalls { get; set; }
        public int? visionScoreAdvantageLaneOpponent { get; set; }
        public int? visionScorePerMinute { get; set; }
        public int? wardTakedowns { get; set; }
        public int? wardTakedownsBefore20M { get; set; }
        public int? wardsGuarded { get; set; }
    }
}
